# frozen_string_literal: true

source "https://rubygems.org"

# GitHub Pages + remote theme
gem "github-pages", group: :jekyll_plugins
gem "just-the-docs", group: :jekyll_plugins

# Dependencies originally in core libraries
gem "base64", group: :jekyll_plugins
gem "csv", group: :jekyll_plugins
gem "webrick", group: :jekyll_plugins
